git add. Moves changes from the working directory to the staging area. ...
git branch. This command is your general-purpose branch administration tool. ...
git checkout. ...
git clean. ...
git clone. ...
git commit. ...
git commit --amend. ...
git config.
